import { LoadingIndicator, TableLoadingRows } from '@/components/shared/LoadingState'
import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { FileText, Loader2, Pencil, Plus } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Textarea } from '@/components/ui/textarea'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { useAuthPermissions } from '@/hooks/useAuthPermissions'
import { useToast } from '@/hooks/use-toast'
import { useTenant } from '@/context/useTenant'
import { createHrDocumentType, fetchHrDocumentTypes, updateHrDocumentType, type DocumentType } from '@/services/hrService'

const empty = { name: '', instructions: '', required: false, active: true, sort_order: 0 }
export function HrDocumentsSettings() {
  const { company } = useTenant(), { hasPermission } = useAuthPermissions(), { toast } = useToast(), qc = useQueryClient()
  const canManage = hasPermission('settings.manage')
  const [editing, setEditing] = useState<DocumentType | null>(null), [open, setOpen] = useState(false), [form, setForm] = useState(empty)
  const query = useQuery({ queryKey: ['hr-document-types', company?.id, 'administrative'], queryFn: () => fetchHrDocumentTypes({ includeInactive: true }) })
  const save = useMutation({ mutationFn: () => editing ? updateHrDocumentType(editing.id, form) : createHrDocumentType(form), onSuccess: () => {
    void qc.invalidateQueries({ queryKey: ['hr-document-types'] }); void qc.invalidateQueries({ queryKey: ['hr-employee-documents'] }); setOpen(false); toast({ title: 'Requisito documental guardado' })
  }, onError: (error: Error) => toast({ title: 'No se pudo guardar', description: error.message, variant: 'destructive' }) })
  return <Card className="config-panel"><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardTitle className="flex items-center gap-2"><FileText className="h-5 w-5 text-brand-orange" />Expedientes de empleados</CardTitle><CardDescription className="mt-2">Define qué documentos solicita esta empresa. PDF, JPEG o PNG, hasta 5 MB por archivo. Desactivar conserva las versiones existentes y no afecta la nómina.</CardDescription></div>{canManage && <Button className="bg-brand-orange text-white hover:bg-brand-orange-strong shrink-0" onClick={() => { setEditing(null); setForm(empty); setOpen(true) }}><Plus className="mr-2 h-4 w-4" />Añadir requisito</Button>}</CardHeader><CardContent>
    {query.isFetching && query.data && <LoadingIndicator message="Actualizando requisitos…" />}{query.isError ? <div role="alert"><p>No se pudieron cargar los requisitos.</p><Button variant="outline" onClick={() => void query.refetch()}>Reintentar</Button></div> : <div className="auna-data-table-shell"><Table><TableHeader><TableRow><TableHead>Documento</TableHead><TableHead>Instrucciones</TableHead><TableHead>Obligatorio</TableHead><TableHead>Estado</TableHead><TableHead>Orden</TableHead><TableHead className="text-right">Acciones</TableHead></TableRow></TableHeader><TableBody>{query.isPending && <TableLoadingRows columns={6} message="Cargando requisitos…" />}{query.data?.items.map(type => <TableRow key={type.id}><TableCell className="font-medium">{type.name}</TableCell><TableCell>{type.instructions || 'Sin instrucciones'}</TableCell><TableCell>{type.required ? 'Sí' : 'Opcional'}</TableCell><TableCell>{type.active ? 'Activo' : 'Inactivo'}</TableCell><TableCell>{type.sort_order}</TableCell><TableCell className="text-right">{canManage && <Button variant="ghost" size="icon" aria-label={`Editar ${type.name}`} onClick={() => { setEditing(type); setForm(type); setOpen(true) }}><Pencil className="h-4 w-4" /></Button>}</TableCell></TableRow>)}{!query.isPending && !query.data?.items.length && <TableRow><TableCell colSpan={6} className="py-8 text-center text-muted-foreground">No hay requisitos. Puedes crear empleados sin documentos hasta configurar los que necesitas.</TableCell></TableRow>}</TableBody></Table></div>}
    <Dialog open={open} onOpenChange={value => { if (!save.isPending) setOpen(value) }}><DialogContent variant="auna"><DialogHeader><DialogTitle>{editing ? 'Editar requisito' : 'Nuevo requisito documental'}</DialogTitle><DialogDescription>Este requisito se aplica solo a {company?.name || 'la empresa activa'}.</DialogDescription></DialogHeader><form onSubmit={e => { e.preventDefault(); save.mutate() }} className="space-y-4"><div><Label htmlFor="hr-type-name">Nombre</Label><Input id="hr-type-name" required maxLength={100} disabled={save.isPending} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div><Label htmlFor="hr-type-instructions">Instrucciones</Label><Textarea id="hr-type-instructions" maxLength={500} disabled={save.isPending} value={form.instructions} onChange={e => setForm({ ...form, instructions: e.target.value })} /></div><div><Label htmlFor="hr-type-order">Orden</Label><Input id="hr-type-order" type="number" min={0} step={1} required disabled={save.isPending} value={form.sort_order} onChange={e => setForm({ ...form, sort_order: Number(e.target.value) })} /></div><div className="flex items-center justify-between"><Label htmlFor="hr-type-required">Obligatorio al crear empleado</Label><Switch id="hr-type-required" disabled={save.isPending} checked={form.required} onCheckedChange={required => setForm({ ...form, required })} /></div><div className="flex items-center justify-between"><Label htmlFor="hr-type-active">Activo</Label><Switch id="hr-type-active" disabled={save.isPending} checked={form.active} onCheckedChange={active => setForm({ ...form, active })} /></div>{editing && !form.active && <p className="text-sm text-muted-foreground">Se dejará de solicitar este documento. Los archivos existentes se conservarán.</p>}<DialogFooter><Button type="button" variant="outline" disabled={save.isPending} onClick={() => setOpen(false)}>Cancelar</Button><Button type="submit" disabled={save.isPending || !form.name.trim()} className="bg-brand-orange text-white hover:bg-brand-orange-strong">{save.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Guardar requisito</Button></DialogFooter></form></DialogContent></Dialog>
  </CardContent></Card>
}
