import { LoadingState, LoadingIndicator } from '@/components/shared/LoadingState'
import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Building2, ChevronDown, Ellipsis, Pencil, Plus, Search, Star } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { useToast } from '@/hooks/use-toast'
import { useTenant } from '@/context/useTenant'
import { useAuth } from '@/context/useAuth'
import type { Branch, Company } from '@/context/AuthContext'
import { createCompany, fetchCompanies, updateCompany, type CreateCompanyPayload } from '@/services/tenantService'

const emptyForm: CreateCompanyPayload = { name: '', code: '', tax_id: '', branch_name: 'Principal', branch_code: 'PRIN' }

export function CompaniesCard({ canManage, activeBranches, onAddBranch }: { canManage: boolean; activeBranches: Branch[]; onAddBranch: () => void }) {
  const { toast } = useToast()
  const client = useQueryClient()
  const { companies, company, setCompany } = useTenant()
  const { refreshUser } = useAuth()
  const [search, setSearch] = useState('')
  const [expanded, setExpanded] = useState(company?.id || '')
  const [createOpen, setCreateOpen] = useState(false)
  const [form, setForm] = useState<CreateCompanyPayload>(emptyForm)
  const [editing, setEditing] = useState<Company | null>(null)
  const [editForm, setEditForm] = useState({ name: '', tax_id: '', address: '', phone: '', active: true })
  const adminQuery = useQuery({ queryKey: ['companies', 'admin'], queryFn: () => fetchCompanies(true), enabled: canManage })
  const rows = canManage ? adminQuery.data || [] : companies
  const filtered = rows.filter((row) => `${row.name} ${row.code} ${row.tax_id || ''} ${row.branches?.map((branch) => branch.name).join(' ') || ''}`.toLocaleLowerCase('es').includes(search.trim().toLocaleLowerCase('es')))
  const refresh = async () => { await refreshUser(); void client.invalidateQueries({ queryKey: ['companies', 'admin'] }) }
  const fail = (error: Error) => toast({ title: 'No se pudo guardar', description: error.message, variant: 'destructive' })
  const createMutation = useMutation({ mutationFn: createCompany, onSuccess: async () => { setCreateOpen(false); setForm(emptyForm); await refresh(); toast({ title: 'Empresa creada' }) }, onError: fail })
  const updateMutation = useMutation({ mutationFn: ({ id, payload }: { id: string; payload: Parameters<typeof updateCompany>[1] }) => updateCompany(id, payload), onSuccess: async () => { setEditing(null); await refresh(); toast({ title: 'Empresa actualizada' }) }, onError: fail })
  const beginEdit = (row: Company) => { setEditing(row); setEditForm({ name: row.name, tax_id: row.tax_id || '', address: row.address || '', phone: row.phone || '', active: row.active !== false }) }
  const create = () => { if (!form.name.trim() || !form.code.trim()) return; createMutation.mutate({ ...form, name: form.name.trim(), code: form.code.trim().toUpperCase(), branch_code: (form.branch_code || 'PRIN').trim().toUpperCase() }) }
  const save = () => { if (!editing || !editForm.name.trim()) return; updateMutation.mutate({ id: editing.id, payload: { ...editForm, name: editForm.name.trim() } }) }

  return <section className="branches-companies">
    <h2 className="sr-only">Empresas y sucursales</h2>
    <div className="auna-page-toolbar compact-filter-toolbar"><label className="auna-control-group branches-search branches-company-search"><Search className="h-4 w-4" /><Input aria-label="Buscar empresas" placeholder="Buscar empresas o sucursales..." value={search} onChange={(event) => setSearch(event.target.value)} /></label><div className="compact-filter-actions">{canManage && <Button className="branches-primary" onClick={() => setCreateOpen(true)}><Plus className="h-4 w-4" /> Nueva empresa</Button>}</div></div>
    {adminQuery.isFetching && adminQuery.data && canManage && <LoadingIndicator message="Actualizando empresas…" />}
    {adminQuery.isLoading && canManage ? <LoadingState variant="cards" message="Cargando empresas…" /> : adminQuery.isError && canManage ? <div className="branches-empty">No se pudieron cargar las empresas. <Button variant="outline" onClick={() => void adminQuery.refetch()}>Reintentar</Button></div> : !filtered.length ? <div className="branches-empty">No hay empresas que coincidan con la búsqueda.</div> : <div className="branches-company-list">{filtered.map((row) => { const open = expanded === row.id; const branchRows = row.branches || (row.id === company?.id ? activeBranches : []); return <article key={row.id} className="branches-company"><div className="branches-company-top"><span className="branches-company-icon"><Building2 /></span><div className="branches-company-title"><strong>{row.name}</strong><small>{row.tax_id ? `NIT ${row.tax_id}` : `Código ${row.code}`}</small></div><span className={`branches-badge branches-badge--${row.active === false ? 'inactive' : 'operating'}`}><i />{row.active === false ? 'Inactiva' : 'Activa'}</span><span className="branches-count"><Star className="h-4 w-4" />{branchRows.length} {branchRows.length === 1 ? 'sucursal' : 'sucursales'}</span><button className="branches-expand" type="button" aria-expanded={open} aria-label={`${open ? 'Contraer' : 'Expandir'} ${row.name}`} onClick={() => setExpanded(open ? '' : row.id)}><ChevronDown className="h-4 w-4" /></button></div>{open && <div className="branches-company-body"><h3>Sucursales</h3>{branchRows.length ? branchRows.map((branch) => <div key={branch.id} className="branches-company-branch"><Building2 className="h-5 w-5" /><div><strong>{branch.name}</strong><small>{branch.address || 'Dirección no registrada'}</small></div>{branch.is_default && <span className="branches-default"><Star className="h-3 w-3" /> Por defecto</span>}<span className={`branches-badge branches-badge--${branch.active === false ? 'inactive' : branch.operational_status === 'MAINTENANCE' ? 'maintenance' : 'operating'}`}><i />{branch.active === false ? 'Inactiva' : branch.operational_status === 'MAINTENANCE' ? 'Mantenimiento' : 'Activa'}</span><span>{branch.manager?.name || 'Sin responsable'}</span><span>{branch.phone || 'Sin teléfono'}</span></div>) : <p className="branches-muted">No hay sucursales visibles en esta empresa.</p>}<div className="branches-company-actions">{row.id === company?.id && canManage && <Button variant="outline" onClick={onAddBranch}><Plus className="h-4 w-4" /> Agregar sucursal</Button>}{row.id !== company?.id && row.active !== false && <Button variant="outline" onClick={() => setCompany(row.id)}>Seleccionar empresa</Button>}{canManage && row.id === company?.id && <Button variant="outline" onClick={() => beginEdit(row)}><Pencil className="h-4 w-4" /> Editar empresa</Button>}</div></div>}</article> })}</div>}

    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent variant="auna" className="branches-dialog"><DialogHeader><DialogTitle>Nueva empresa</DialogTitle><DialogDescription>Se crea con su sucursal principal y quedas asignado a ella. El código no se podrá cambiar.</DialogDescription></DialogHeader><div className="branches-form branches-form-two"><label>Nombre *<Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Código *<Input maxLength={20} value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase() })} /></label><label>NIT<Input value={form.tax_id || ''} onChange={(event) => setForm({ ...form, tax_id: event.target.value })} /></label><label>Sucursal principal<Input value={form.branch_name || ''} onChange={(event) => setForm({ ...form, branch_name: event.target.value })} /></label><label>Código de sucursal<Input maxLength={10} value={form.branch_code || ''} onChange={(event) => setForm({ ...form, branch_code: event.target.value.toUpperCase() })} /></label></div><DialogFooter><Button variant="outline" onClick={() => setCreateOpen(false)}>Cancelar</Button><Button className="branches-primary" onClick={create} disabled={createMutation.isPending || !form.name.trim() || !form.code.trim()}>Crear empresa</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(editing)} onOpenChange={(open) => { if (!open) setEditing(null) }}><DialogContent variant="auna" className="branches-dialog"><DialogHeader><DialogTitle>Editar empresa</DialogTitle><DialogDescription>El código {editing?.code} se mantiene para conservar la numeración documental.</DialogDescription></DialogHeader><div className="branches-form"><label>Nombre *<Input value={editForm.name} onChange={(event) => setEditForm({ ...editForm, name: event.target.value })} /></label><label>NIT<Input value={editForm.tax_id} onChange={(event) => setEditForm({ ...editForm, tax_id: event.target.value })} /></label><label>Dirección<Input value={editForm.address} onChange={(event) => setEditForm({ ...editForm, address: event.target.value })} /></label><label>Teléfono<Input value={editForm.phone} onChange={(event) => setEditForm({ ...editForm, phone: event.target.value })} /></label><label>Estado<select className="auna-control auna-control-select" value={editForm.active ? 'active' : 'inactive'} onChange={(event) => setEditForm({ ...editForm, active: event.target.value === 'active' })}><option value="active">Activa</option><option value="inactive">Inactiva</option></select></label></div><DialogFooter><Button variant="outline" onClick={() => setEditing(null)}>Cancelar</Button><Button className="branches-primary" onClick={save} disabled={updateMutation.isPending || !editForm.name.trim()}>Guardar cambios</Button></DialogFooter></DialogContent></Dialog>
  </section>
}
