import { LoadingIndicator, TableLoadingRows } from '@/components/shared/LoadingState'
import { MetricStrip } from '@/components/shared/MetricStrip'
import { CompactFilterPanel } from '@/components/shared/CompactFilterPanel'
import { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ChevronLeft, ChevronRight, MapPin, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'
import { useToast } from '@/hooks/use-toast'
import { useTenant } from '@/context/useTenant'
import type { Branch } from '@/context/AuthContext'
import { createLocation, createWarehouse, deleteLocation, deleteWarehouse, fetchWarehouses, setSalesLocation, updateLocation, updateWarehouse, WAREHOUSE_KIND_LABELS, type Warehouse, type WarehouseKind, type WarehousePayload, type StockLocation } from '@/services/warehouseService'
import { filterWarehouses, isWarehouseOperational } from './branchOverview.mjs'

const emptyForm: WarehousePayload = { name: '', kind: 'BODEGA', dispatch_priority: 100 }
type DeleteTarget = { type: 'warehouse'; row: Warehouse } | { type: 'location'; row: StockLocation }

export function WarehousesCard({ canManage, branches }: { canManage: boolean; branches: Branch[] }) {
  const { toast } = useToast()
  const client = useQueryClient()
  const { branch } = useTenant()
  const [search, setSearch] = useState('')
  const [branchId, setBranchId] = useState('all')
  const [status, setStatus] = useState('all')
  const [page, setPage] = useState(1)
  const [createOpen, setCreateOpen] = useState(false)
  const [form, setForm] = useState<WarehousePayload>(emptyForm)
  const [editing, setEditing] = useState<Warehouse | null>(null)
  const [detailId, setDetailId] = useState<string | null>(null)
  const [locationForm, setLocationForm] = useState({ name: '', dispatch_priority: 100 })
  const [locationOpen, setLocationOpen] = useState(false)
  const [deleteTarget, setDeleteTarget] = useState<DeleteTarget | null>(null)

  const query = useQuery({ queryKey: ['warehouses', 'all', branch?.company_id], queryFn: () => fetchWarehouses('all') })
  const warehouses = query.data || []
  const filtered = useMemo(() => filterWarehouses(warehouses, { search, branchId, status }) as Warehouse[], [warehouses, search, branchId, status])
  const pageSize = 10
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize))
  const currentPage = Math.min(page, totalPages)
  const visible = filtered.slice((currentPage - 1) * pageSize, currentPage * pageSize)
  const detail = warehouses.find((row) => row.id === detailId)
  const stockUnits = warehouses.reduce((sum, row) => sum + (row.stock_units || 0), 0)
  const invalidate = () => void client.invalidateQueries({ queryKey: ['warehouses'] })
  const fail = (error: Error) => toast({ title: 'No se pudo guardar', description: error.message, variant: 'destructive' })
  const createMutation = useMutation({ mutationFn: createWarehouse, onSuccess: () => { setCreateOpen(false); setForm(emptyForm); invalidate(); toast({ title: 'Almacén creado' }) }, onError: fail })
  const updateMutation = useMutation({ mutationFn: ({ id, payload }: { id: string; payload: Parameters<typeof updateWarehouse>[1] }) => updateWarehouse(id, payload), onSuccess: () => { setEditing(null); invalidate(); toast({ title: 'Almacén actualizado' }) }, onError: fail })
  const deleteWarehouseMutation = useMutation({ mutationFn: deleteWarehouse, onSuccess: () => { setDetailId(null); setDeleteTarget(null); invalidate(); toast({ title: 'Almacén eliminado' }) }, onError: fail })
  const createLocationMutation = useMutation({ mutationFn: ({ warehouseId, name, dispatch_priority }: { warehouseId: string; name: string; dispatch_priority: number }) => createLocation(warehouseId, { name, dispatch_priority }), onSuccess: () => { setLocationOpen(false); setLocationForm({ name: '', dispatch_priority: 100 }); invalidate(); toast({ title: 'Ubicación creada' }) }, onError: fail })
  const updateLocationMutation = useMutation({ mutationFn: ({ id, payload }: { id: string; payload: Parameters<typeof updateLocation>[1] }) => updateLocation(id, payload), onSuccess: invalidate, onError: fail })
  const salesMutation = useMutation({ mutationFn: setSalesLocation, onSuccess: invalidate, onError: fail })
  const deleteLocationMutation = useMutation({ mutationFn: deleteLocation, onSuccess: () => { setDeleteTarget(null); invalidate(); toast({ title: 'Ubicación eliminada' }) }, onError: fail })
  const busy = createMutation.isPending || updateMutation.isPending || deleteWarehouseMutation.isPending || updateLocationMutation.isPending || deleteLocationMutation.isPending
  const canEdit = (row: Warehouse) => canManage && row.branch_id === branch?.id
  const beginEdit = (row: Warehouse) => { setEditing(row); setForm({ name: row.name, kind: row.kind, dispatch_priority: row.dispatch_priority, notes: row.notes || '' }) }
  const save = () => { if (!editing || !form.name.trim()) return; updateMutation.mutate({ id: editing.id, payload: { name: form.name.trim(), kind: form.kind, dispatch_priority: form.dispatch_priority, notes: form.notes || '' } }) }

  return <section className="branches-warehouses">
    <h2 className="sr-only">Almacenes</h2>
    <MetricStrip loading={query.isLoading} label="Resumen de almacenes" items={[{label:'Almacenes',value:warehouses.length},{label:'Ubicaciones',value:warehouses.reduce((sum,row) => sum + row.locations.length,0)},{label:'Unidades en existencias',value:stockUnits.toLocaleString('es-GT')},{label:'Almacenes operativos',value:warehouses.filter(isWarehouseOperational).length}]} />
      <CompactFilterPanel actions={<>{canManage && branch && <Button className="branches-primary" onClick={() => { setForm(emptyForm); setCreateOpen(true) }}><Plus className="h-4 w-4" /> Nuevo almacén</Button>}</>} title="Filtros de almacenes" activeCount={Number(Boolean(search.trim())) + Number(branchId !== 'all') + Number(status !== 'all')} onClear={() => {setSearch('');setBranchId('all');setStatus('all');setPage(1)}} appliedFilters={[...(search.trim() ? [{label: `Búsqueda: ${search}`,onRemove: () => {setSearch('');setPage(1)}}] : []),...(branchId !== 'all' ? [{label: `Sucursal: ${branches.find(item => item.id === branchId)?.name || 'Seleccionada'}`,onRemove: () => {setBranchId('all');setPage(1)}}] : []),...(status !== 'all' ? [{label: `Estado: ${status === 'active' ? 'Operativos' : 'Inactivos'}`,onRemove: () => {setStatus('all');setPage(1)}}] : [])]} search={<label className="auna-control-group branches-search"><Search className="h-4 w-4" /><Input aria-label="Buscar almacenes" placeholder="Buscar almacén, sucursal o ubicación..." value={search} onChange={(event) => { setSearch(event.target.value); setPage(1) }} /></label>}>
        <select className="auna-control auna-control-select" aria-label="Filtrar por sucursal" value={branchId} onChange={(event) => { setBranchId(event.target.value); setPage(1) }}><option value="all">Todas las sucursales</option>{branches.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>
        <select className="auna-control auna-control-select" aria-label="Filtrar por estado" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1) }}><option value="all">Todos los estados</option><option value="active">Operativos</option><option value="inactive">Inactivos</option></select>
      </CompactFilterPanel>
    <div className="branches-warehouse-table"><table><thead><tr><th>Nombre del almacén</th><th>Sucursal</th><th>Ubicaciones</th><th>Tipo</th><th>Existencias</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{query.isLoading && <TableLoadingRows columns={7} message="Cargando almacenes…" />}{visible.map((row) => <tr key={row.id}><td><strong>{row.name}</strong><small>{row.code}</small></td><td>{row.branch?.name || branches.find((item) => item.id === row.branch_id)?.name || '—'}</td><td>{row.locations.length}</td><td>{WAREHOUSE_KIND_LABELS[row.kind]}</td><td>{(row.stock_units || 0).toLocaleString('es-GT')} unidades</td><td><span className={`branches-badge branches-badge--${isWarehouseOperational(row) ? 'operating' : 'inactive'}`}><i />{isWarehouseOperational(row) ? 'Operativo' : row.branch?.active === false ? 'Sucursal inactiva' : 'Inactivo'}</span></td><td><div className="branches-row-actions"><Button variant="outline" size="sm" onClick={() => setDetailId(row.id)}>Ver</Button>{canEdit(row) && <Button variant="outline" size="icon" title={`Editar ${row.name}`} aria-label={`Editar ${row.name}`} onClick={() => beginEdit(row)}><Pencil className="h-4 w-4" /></Button>}</div></td></tr>)}</tbody></table>{query.isFetching && query.data && <LoadingIndicator message="Actualizando almacenes…" />}{query.isLoading ? null : query.isError ? <div className="branches-empty">No se pudieron cargar los almacenes. <Button variant="outline" onClick={() => void query.refetch()}>Reintentar</Button></div> : !visible.length && <div className="branches-empty">No hay almacenes que coincidan con los filtros.</div>}</div>
    <footer className="branches-pagination"><span>Mostrando {visible.length ? (currentPage - 1) * pageSize + 1 : 0} a {Math.min(currentPage * pageSize, filtered.length)} de {filtered.length} almacenes</span><div><button type="button" disabled={currentPage <= 1} onClick={() => setPage(currentPage - 1)} aria-label="Página anterior"><ChevronLeft className="h-4 w-4" /></button>{Array.from({ length: totalPages }, (_, index) => <button type="button" key={index} data-active={index + 1 === currentPage} onClick={() => setPage(index + 1)}>{index + 1}</button>)}<button type="button" disabled={currentPage >= totalPages} onClick={() => setPage(currentPage + 1)} aria-label="Página siguiente"><ChevronRight className="h-4 w-4" /></button></div></footer>

    <Dialog open={createOpen} onOpenChange={setCreateOpen}><DialogContent variant="auna" className="branches-dialog"><DialogHeader><DialogTitle>Nuevo almacén</DialogTitle><DialogDescription>Se creará en {branch?.name}. Se añade automáticamente la ubicación GENERAL.</DialogDescription></DialogHeader><WarehouseFields form={form} setForm={setForm} /><DialogFooter><Button variant="outline" onClick={() => setCreateOpen(false)}>Cancelar</Button><Button className="branches-primary" disabled={!form.name.trim() || createMutation.isPending} onClick={() => createMutation.mutate({ ...form, name: form.name.trim() })}>Crear almacén</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(editing)} onOpenChange={(open) => { if (!open) setEditing(null) }}><DialogContent variant="auna" className="branches-dialog"><DialogHeader><DialogTitle>Editar almacén</DialogTitle><DialogDescription>{editing?.code} · {editing?.branch?.name}</DialogDescription></DialogHeader><WarehouseFields form={form} setForm={setForm} /><div className="branches-form-actions">{editing && <><Button variant="outline" disabled={busy} onClick={() => updateMutation.mutate({ id: editing.id, payload: { active: !editing.active } })}>{editing.active ? 'Desactivar' : 'Reactivar'}</Button>{!editing.is_default && <Button variant="outline" disabled={busy} onClick={() => updateMutation.mutate({ id: editing.id, payload: { is_default: true } })}>Predeterminar</Button>}{!editing.is_receiving && <Button variant="outline" disabled={busy} onClick={() => updateMutation.mutate({ id: editing.id, payload: { is_receiving: true } })}>Marcar recepción</Button>}<Button variant="destructive" disabled={busy || editing.is_default} onClick={() => setDeleteTarget({ type: 'warehouse', row: editing })}><Trash2 className="mr-1 h-4 w-4" /> Eliminar</Button></>}</div><DialogFooter><Button variant="outline" onClick={() => setEditing(null)}>Cancelar</Button><Button className="branches-primary" disabled={busy || !form.name.trim()} onClick={save}>Guardar cambios</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(detail)} onOpenChange={(open) => { if (!open) setDetailId(null) }}><DialogContent variant="auna" className="branches-dialog"><DialogHeader><DialogTitle>{detail?.name}</DialogTitle><DialogDescription>{detail?.branch?.name} · {detail?.code} · {(detail?.stock_units || 0).toLocaleString('es-GT')} unidades</DialogDescription></DialogHeader>{detail && <><div className="branches-detail"><p><span>Tipo</span><strong>{WAREHOUSE_KIND_LABELS[detail.kind]}</strong></p><p><span>Prioridad</span><strong>{detail.dispatch_priority}</strong></p><p><span>Predeterminado</span><strong>{detail.is_default ? 'Sí' : 'No'}</strong></p><p><span>Recepción</span><strong>{detail.is_receiving ? 'Sí' : 'No'}</strong></p></div><h3>Ubicaciones ({detail.locations.length})</h3><div className="branches-locations">{detail.locations.map((location) => <div key={location.id} className="branches-location"><div><MapPin className="h-4 w-4" /><strong>{location.name || location.code}</strong><span>{location.code}</span>{location.is_default && <small>Predeterminada</small>}{location.is_sales && <small>Punto de venta</small>}</div>{canEdit(detail) && <div><Button variant="outline" size="sm" disabled={busy} onClick={() => salesMutation.mutate(location.id)}>{location.is_sales ? 'Quitar POS' : 'Usar en POS'}</Button><Button variant="outline" size="sm" disabled={busy} onClick={() => updateLocationMutation.mutate({ id: location.id, payload: { pickable: !location.pickable } })}>{location.pickable ? 'No despachar' : 'Permitir despacho'}</Button>{!location.is_default && <Button variant="outline" size="icon" title="Eliminar ubicación" aria-label={`Eliminar ubicación ${location.name || location.code}`} disabled={busy} onClick={() => setDeleteTarget({ type: 'location', row: location })}><Trash2 className="h-4 w-4" /></Button>}</div>}</div>)}</div></>}{detail && canEdit(detail) && <DialogFooter><Button variant="outline" onClick={() => setLocationOpen(true)}><Plus className="mr-1 h-4 w-4" /> Nueva ubicación</Button><Button className="branches-primary" onClick={() => { beginEdit(detail); setDetailId(null) }}>Editar almacén</Button></DialogFooter>}</DialogContent></Dialog>
    <Dialog open={locationOpen} onOpenChange={setLocationOpen}><DialogContent variant="auna" className="branches-dialog"><DialogHeader><DialogTitle>Nueva ubicación</DialogTitle><DialogDescription>Dentro de {detail?.name}. El código se genera del nombre.</DialogDescription></DialogHeader><div className="branches-form"><label>Nombre *<Input value={locationForm.name} onChange={(event) => setLocationForm({ ...locationForm, name: event.target.value })} /></label><label>Prioridad de despacho<Input type="number" value={locationForm.dispatch_priority} onChange={(event) => setLocationForm({ ...locationForm, dispatch_priority: Number(event.target.value) })} /></label></div><DialogFooter><Button variant="outline" onClick={() => setLocationOpen(false)}>Cancelar</Button><Button className="branches-primary" disabled={!locationForm.name.trim() || createLocationMutation.isPending} onClick={() => detail && createLocationMutation.mutate({ warehouseId: detail.id, name: locationForm.name.trim(), dispatch_priority: locationForm.dispatch_priority })}>Crear ubicación</Button></DialogFooter></DialogContent></Dialog>
    <AlertDialog open={Boolean(deleteTarget)} onOpenChange={(open) => { if (!open) setDeleteTarget(null) }}><AlertDialogContent variant="auna" className="branches-dialog"><AlertDialogHeader><AlertDialogTitle>¿Eliminar {deleteTarget?.type === 'warehouse' ? 'almacén' : 'ubicación'}?</AlertDialogTitle><AlertDialogDescription>Solo se permite si no contiene existencias ni movimientos que lo referencien. Esta acción no se puede deshacer.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction className="bg-destructive text-destructive-foreground" disabled={busy} onClick={(event) => { event.preventDefault(); if (deleteTarget?.type === 'warehouse') deleteWarehouseMutation.mutate(deleteTarget.row.id); if (deleteTarget?.type === 'location') deleteLocationMutation.mutate(deleteTarget.row.id) }}>Eliminar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </section>
}

function WarehouseFields({ form, setForm }: { form: WarehousePayload; setForm: (form: WarehousePayload) => void }) {
  return <div className="branches-form"><label>Nombre *<Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Tipo<select className="auna-control auna-control-select" value={form.kind || 'BODEGA'} onChange={(event) => setForm({ ...form, kind: event.target.value as WarehouseKind })}>{Object.entries(WAREHOUSE_KIND_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Prioridad de despacho<Input type="number" value={form.dispatch_priority || 100} onChange={(event) => setForm({ ...form, dispatch_priority: Number(event.target.value) })} /></label><label>Notas<Input value={form.notes || ''} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label></div>
}
