import { LoadingState, LoadingIndicator } from '@/components/shared/LoadingState'
import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { FileText, Download, Eye } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { useAuthPermissions } from '@/hooks/useAuthPermissions'
import { useToast } from '@/hooks/use-toast'
import { accessEmployeeDocument, archiveEmployeeDocument, fetchEmployeeDocuments, uploadEmployeeDocument, type DocumentVersion } from '@/services/hrService'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog'

export function EmployeeDocuments({ employeeId }: { employeeId: string }) {
  const { hasPermission } = useAuthPermissions(), { toast } = useToast(), qc = useQueryClient()
  const [confirmation, setConfirmation] = useState<DocumentVersion | null>(null)
  const [pendingUpload, setPendingUpload] = useState<{ file: File; typeId: string } | null>(null)
  const query = useQuery({ queryKey: ['hr-employee-documents', employeeId], queryFn: () => fetchEmployeeDocuments(employeeId) })
  const operation = useMutation({ onMutate: action => { if ('file' in action) setPendingUpload(action) }, mutationFn: async (action: { file: File; typeId: string } | { document: DocumentVersion }) => {
    if ('file' in action) return uploadEmployeeDocument(employeeId, action.typeId, action.file)
    return archiveEmployeeDocument(employeeId, action.document.id, !!action.document.archived_at)
  }, onSuccess: () => { setPendingUpload(null); setConfirmation(null); qc.invalidateQueries({ queryKey: ['hr-employee-documents', employeeId] }); qc.invalidateQueries({ queryKey: ['hr-employee-overview', employeeId] }); qc.invalidateQueries({ queryKey: ['hr-employee-history', employeeId] }); toast({ title: 'Expediente documental actualizado' }) }, onError: (error: Error) => { qc.invalidateQueries({ queryKey: ['hr-employee-documents', employeeId] }); toast({ title: 'No se pudo actualizar el documento', description: error.message, variant: 'destructive' }) } })
  const access = useMutation({ mutationFn: async ({ item, download }: { item: DocumentVersion; download: boolean }) => {
    const result = await accessEmployeeDocument(employeeId, item.id, download)
    const link = document.createElement('a'); link.href = result.url; link.target = '_blank'; link.rel = 'noopener noreferrer'; link.referrerPolicy = 'no-referrer'; link.click()
  }, onError: (error: Error) => toast({ title: 'No se pudo abrir el archivo', description: error.message, variant: 'destructive' }) })
  if (query.isPending) return <Card className="hr-panel"><CardHeader><CardTitle>Documentos del expediente</CardTitle></CardHeader><CardContent><LoadingState variant="cards" message="Cargando documentos…" /></CardContent></Card>
  if (query.isError) return <div><p>No se pudieron cargar los documentos.</p><Button variant="outline" onClick={() => query.refetch()}>Reintentar</Button></div>
  return <Card className="hr-panel"><CardHeader><CardTitle><FileText />Documentos del expediente</CardTitle><p className="text-sm text-muted-foreground">PDF, JPEG o PNG · máximo 5 MB. Reemplazar conserva la versión anterior. Los enlaces de acceso caducan.</p></CardHeader><CardContent className="space-y-4">{query.isFetching && <LoadingIndicator message="Actualizando documentos…" />}
    {query.data.requirements.map(type => <div className="hr-document-row" key={type.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><strong>{type.name}</strong><p className="text-xs text-muted-foreground">{type.instructions || (type.required ? 'Requerido' : 'Opcional')}</p></div>{hasPermission('hr.documents.manage') && <label className="cursor-pointer text-brand-orange">Cargar o reemplazar<input type="file" className="sr-only" disabled={operation.isPending} accept="application/pdf,image/jpeg,image/png" aria-label={`Cargar ${type.name}`} onChange={e => { const file = e.target.files?.[0]; if (file) operation.mutate({ typeId: type.id, file }); e.target.value = '' }} /></label>}</div><p className="mt-2 text-xs">{query.data.items.some(item => item.type_id === type.id && !item.archived_at) ? 'Documento vigente disponible' : type.required ? 'Pendiente de carga' : 'Sin documento'}</p></div>)}
    {pendingUpload && <div className="hr-document-row"><p className="text-sm break-all">{operation.isPending ? 'Cargando' : 'Carga pendiente'}: {pendingUpload.file.name}</p>{!operation.isPending && <div className="mt-2 flex gap-2"><Button size="sm" variant="outline" disabled={!query.data.requirements.some(type => type.id === pendingUpload.typeId)} onClick={() => operation.mutate(pendingUpload)}>Reintentar carga</Button><Button size="sm" variant="ghost" onClick={() => setPendingUpload(null)}>Descartar selección</Button></div>}{!query.data.requirements.some(type => type.id === pendingUpload.typeId) && <p className="text-xs text-destructive">El tipo fue desactivado. Conservamos la selección, pero debes elegir un tipo activo para cargarlo.</p>}</div>}
    {!query.data.requirements.length && <p className="text-sm text-muted-foreground">No hay tipos de documento activos para esta empresa.</p>}
    {query.data.items.map(item => <div key={item.id} className="hr-document-row flex flex-wrap items-center justify-between gap-3"><div className="min-w-0"><p className="break-all font-medium">{item.original_name}</p><p className="text-xs text-muted-foreground">{item.archived_at ? 'Versión archivada' : 'Vigente'} · {new Date(item.created_at).toLocaleDateString('es-GT')} · {(item.size_bytes / 1024).toFixed(0)} KB</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" disabled={access.isPending} onClick={() => access.mutate({ item, download: false })}><Eye className="mr-1 h-4 w-4" />Ver</Button><Button variant="outline" size="sm" disabled={access.isPending} onClick={() => access.mutate({ item, download: true })}><Download className="mr-1 h-4 w-4" />Descargar</Button>{hasPermission('hr.documents.archive') && <Button variant="outline" size="sm" disabled={operation.isPending} onClick={() => setConfirmation(item)}>{item.archived_at ? 'Restaurar' : 'Archivar'}</Button>}</div></div>)}
    <AlertDialog open={!!confirmation} onOpenChange={open => { if (!open && !operation.isPending) setConfirmation(null) }}><AlertDialogContent variant="auna"><AlertDialogHeader><AlertDialogTitle>{confirmation?.archived_at ? 'Restaurar documento' : 'Archivar documento'}</AlertDialogTitle><AlertDialogDescription>{confirmation?.archived_at ? 'Se restaurará solo si no existe otra versión vigente del mismo tipo.' : 'El archivo se conserva en el historial. Si es requerido, el expediente quedará pendiente hasta cargar o restaurar una versión.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={operation.isPending}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={operation.isPending} onClick={e => { e.preventDefault(); if (confirmation) operation.mutate({ document: confirmation }) }}>{operation.isPending ? 'Guardando…' : 'Confirmar'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </CardContent></Card>
}
